REM INSERTING into SDS_TIPO_MATERIALES_TML
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('1','AEWOHxC','NKgbqpa');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('2','ywVfhgM','csmEzBH');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('3','ROyriwd','rrBusjh');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('4','fbmLXRs','oEHnisd');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('5','wFwYMBT','sMohgcu');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('7','vbmfBZN','PTnlvVy');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('9','ARWIcGH','Umjwvii');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('10','pUgqAzR','kHBYXso');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('6','jjkkjk','jjjj');
Insert into SDS_TIPO_MATERIALES_TML (TML_CODIGO,TML_NOMBRE,TML_DESCRIPCION) values ('8','nsnana','uu1u1');
