REM INSERTING into SDS_ORDEN_PRORIDAD_OPA
Insert into SDS_ORDEN_PRORIDAD_OPA (OPA_CODIGO,OPA_NOMBRE) values (1,'baja');
Insert into SDS_ORDEN_PRORIDAD_OPA (OPA_CODIGO,OPA_NOMBRE) values (2,'media');
Insert into SDS_ORDEN_PRORIDAD_OPA (OPA_CODIGO,OPA_NOMBRE) values (3,'alta');
